on: [push, pull_request, workflow_dispatch]

env:
  archive_name: firmware-${{ vars.GITHUB_RUN_NUMBER }}

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: ${{ vars.archive_name }}
